stages:
  # - test
  - build
  - deploy

cache:
  key: $CI_PROJECT_NAME
  paths:
    - node_modules/

# -------
#  JOBS
# -------

build:
  stage: build
  artifacts:
    paths:
      - dist/
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$CI_JOB_ID"
  script:
    - npm install
    - npm run build

publish:
  stage: deploy
  dependencies:
    - build
  only:
    - tags
  script:
    - echo "//${NPM_REGISTRY_DOMAIN}/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
    - npm publish
